# General Jekyll Config
highlighter: pygments
url: http://theconnman.com
lsi: false
exclude: [LICENSE, CNAME, README.md, .gitignore, Gemfile, Gemfile.lock]

collections:
  pages:
    output: true
    permalink: /:path/

include: ['_pages']
